[package]
edition = "2018"
name = "pando"
version = "0.1.0"

[dependencies]
clipboard = "0.5.0"
dirs = "3.0.2"
serde_json = "1.0.59"

[dependencies.druid]
branch = "serde-hotfix"
features = ["im", "serde"]
git = "https://github.com/Kethku/druid"

[dependencies.serde]
features = ["derive"]
serde_json = "1.0.59"
version = "1.0.126"

[dependencies.serde.serde]
features = ["derive"]
version = "1.0.126"
